# Generated by Django 5.1.3 on 2025-02-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('userid', models.AutoField(db_column='userid', primary_key=True, serialize=False)),
                ('partnerid', models.IntegerField(blank=True, db_column='partnerid', null=True)),
                ('username', models.CharField(db_column='username', default='defaultuser', max_length=150, unique=True)),
                ('email', models.EmailField(db_column='email', default='user@example.com', max_length=254, unique=True)),
                ('firstlastname', models.CharField(db_column='firstlastname', default='First Last', max_length=255)),
                ('password', models.TextField(db_column='password', default='')),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('dietid', models.AutoField(db_column='dietid', primary_key=True, serialize=False)),
                ('dietname', models.CharField(db_column='dietname', default='General', max_length=255, unique=True)),
            ],
            options={
                'db_table': 'diet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipeid', models.AutoField(db_column='recipeid', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', default='Untitled Recipe', max_length=255)),
                ('ingredients', models.TextField(db_column='ingredients', default='No ingredients listed')),
                ('instructions', models.TextField(db_column='instructions', default='No instructions provided')),
                ('image_name', models.CharField(blank=True, db_column='image_name', max_length=255, null=True)),
                ('cleaned_ingredients', models.TextField(db_column='cleaned_ingredients', default='')),
            ],
            options={
                'db_table': 'recipe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecipeDiet',
            fields=[
                ('recipedietid', models.AutoField(db_column='recipedietid', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'recipe_diet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SavedRecipe',
            fields=[
                ('savedid', models.AutoField(db_column='savedid', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'saved_recipe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserDiet',
            fields=[
                ('userdietid', models.AutoField(db_column='userdietid', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'user_diet',
                'managed': False,
            },
        ),
    ]
