# Generated by Django 5.1.2 on 2024-10-24 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tastebuds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeDiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tastebuds.diet')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tastebuds.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='diets',
            field=models.ManyToManyField(through='tastebuds.RecipeDiet', to='tastebuds.diet'),
        ),
    ]
