# Generated by Django 5.1.2 on 2024-10-30 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tastebuds', '0002_recipediet_recipe_diets'),
        ('tastebuds', '0002_users'),
    ]

    operations = [
    ]
