# Generated by Django 5.1.2 on 2024-10-30 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tastebuds', '0003_merge_0002_recipediet_recipe_diets_0002_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
