# Generated by Django 5.1.6 on 2025-03-02 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tastebuds', '0004_alter_customuser_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='partnerid',
        ),
        migrations.AddField(
            model_name='customuser',
            name='partner',
            field=models.OneToOneField(blank=True, db_column='partnerid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
