# Generated by Django 5.1.6 on 2025-03-03 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tastebuds', '0006_category_recipecategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='userid',
            new_name='id',
        ),
    ]
