# Generated by Django 5.1.6 on 2025-03-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tastebuds', '0007_rename_userid_customuser_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(db_column='email', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(db_column='username', max_length=150, unique=True),
        ),
    ]
