# Generated by Django 5.1.6 on 2025-03-25 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tastebuds', '0008_alter_customuser_options_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='tastebuds_customuser',
        ),
    ]
