# Generated by Django 5.1.6 on 2025-03-25 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tastebuds', '0009_alter_customuser_options_alter_customuser_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='CustomUser',
        ),
    ]
