# Generated by Django 5.1.6 on 2025-03-25 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tastebuds', '0010_alter_customuser_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table=None,
        ),
    ]
