# Generated by Django 5.1.6 on 2025-04-01 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tastebuds', '0011_alter_customuser_options_alter_customuser_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateRecipe',
            fields=[
                ('privateRecipeID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('imageName', models.TextField(blank=True, null=True)),
                ('cleaned_ingredients', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
