# Generated by Django 5.1.6 on 2025-04-02 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tastebuds', '0012_privaterecipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_partner_requests', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_partner_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'partner_request',
                'unique_together': {('from_user', 'to_user')},
            },
        ),
    ]
